version: "3"

services:
  auth:
      build:
        context: ./Auth
        dockerfile: Dockerfile
      ports:
        - "3001:3001"
      env_file:
        - .env
      # volumes:
      #   - .:/usr/src/datn/user
  user:
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/user

  cart:
    build:
      context: ./Cart
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/cart

  shop:
    build:
      context: ./Shop
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/shop

  category:
    build:
      context: ./Category
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/category

  product:
    build:
      context: ./Product
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/product

  review:
    build:
      context: ./Review
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/review

  promotion:
    build:
      context: ./Promotion
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/promotion

  order:
    build:
      context: ./Order
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/order

  widget:
    build:
      context: ./Widget
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/widget
  
  payment:
    build:
      context: ./Payment
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/datn/payment
