# Use the official Redis image from the Docker Hub
FROM redis:latest

# Maintain the author
# LABEL maintainer="your-email@example.com"

# Copy the custom Redis configuration file to the container
# Or, you can use the default config of Redis
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the Redis port
EXPOSE 6379

ENV REDIS_PASSWORD=ganwjeg9j4_uMg32PLg9fa31fafs

# Run Redis with the custom configuration file
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
CMD ["redis-server"]



